### ISSUE TITLE
Add c++ programs

### ISSUE THREAD

**Issue by Defcon27** [Defcon27/Open-Algorithms#1]
Contribute algorithms implemented in C++ or C++STL

**Comment by Rituraj-commits** [comment]
Can I work on this issue

**Comment by Defcon27** [comment]
sure

**Comment by shibrahmachari** [comment]
can i work on this?

**Comment by probhav** [comment]
I'll like to claim the issue!

**Comment by sharleenclement** [comment]
Hey @Defcon27 assign it to me?

**Comment by pawki07** [comment]
Hey, I would like to contribute to this issue. Please assign it to me.

**Comment by chelsi-001011** [comment]
@Defcon27 Can we add any algorithm?

**Comment by Defcon27** [comment]
> @Defcon27 Can we add any algorithm?

Non Duplicated ones please
